version: '3'

services:
  jackett-sync:
    network_mode: host
    image: allergicduck/jackett-sync
    environment:
      - JACKETT_URL=http://172.18.0.2:9117
      - JACKETT_ALTURL=http://localhost:9117
      - JACKETT_KEY=z9ukkyubjmvzm8ey3jyxyywrva1py4cb
      - LIDARR_URL=http://172.18.0.2:8686
      - LIDARR_KEY=9280f2659f694f659ba87249df5b1a2f
      - RADARR_URL=http://172.18.0.2:7878
      - RADARR_KEY=0b8e12562f914a0cb7354f7f9a0731a4
      - SONARR_URL=http://172.18.0.2:8989
      - SONARR_KEY=7d650afd0a574d1e8c1665c290c011b9